template:
  path: alb-redirector.yaml
stack_name: agora-staging-alb-redirector
stack_tags:
  Environment: "staging"
dependencies:
  - staging/agora.yaml
parameters:
  ListenerArn: TBD
  RedirectFromHost: "agora-staging.agora-ampad.org"
  RedirectToHost: "agora-staging.adknowledgeportal.org"
